name = "travel-planner-api"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
RESEND_API_KEY = "re_i66p1BLV_CJztt9kNJrF4jro7JwwypTRE"
FROM_EMAIL = "Travel Planner <onboarding@resend.dev>"

[[kv_namespaces]]
binding = "TRAVEL_KV"
id = "16296366ae074386aea50012e99fc722"
preview_id = "16296366ae074386aea50012e99fc722"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "travel-planner-photos"
